# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: supershift
service: karoo-lodge-backend

package:
  patterns:
    - 'handlers/**'
    - 'getApiKey.js'
    - 'getUploadUrl.js'
    - 'saveImage.js'
    - 'listImages.js'
    - '!node_modules/**'
    - '!src/**'
    - '!dist/**'
    - '!.git/**'
    - '!.serverless/**'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    S3_REGION: eu-west-1
    COGNITO_USER_POOL_ID: us-east-1_fzogF46tc
    S3_BUCKET: barrydale-media
    UPLOAD_API_KEY: 79dc174817e715e1f30906b9f4d09be74d0323d8bf387962c95f728762e60159
    CLOUDFRONT_URL: https://d3ieyce90rkgk7.cloudfront.net
    DYNAMO_TABLE: MediaFiles
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:GetObjectAcl
            - s3:PutObjectAcl
            - s3:GetSignedUrl
          Resource:
            - arn:aws:s3:::barrydale-media/*
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.DYNAMO_TABLE}

functions:
  getApiKey:
    handler: handlers/auth.getApiKey
    events:
      - http:
          path: api/get-api-key
          method: post
          cors: true
      - http:
          path: api/get-api-key
          method: options
          cors: true

  getUploadUrl:
    handler: handlers/upload.getUploadUrl
    events:
      - http:
          path: api/upload-url
          method: post
          cors: true
      - http:
          path: api/upload-url
          method: options
          cors: true

  saveImage:
    handler: handlers/saveImage.saveImage
    events:
      - http:
          path: api/save-image
          method: post
          cors: true
      - http:
          path: api/save-image
          method: options
          cors: true

  listImages:
    handler: handlers/listImages.listImages
    events:
      - http:
          path: api/list-images
          method: get
          cors: true
      - http:
          path: api/list-images
          method: options
          cors: true


resources:
  Resources:
    MediaFilesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MediaFiles
        AttributeDefinitions:
          - AttributeName: fileUrl
            AttributeType: S
        KeySchema:
          - AttributeName: fileUrl
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
